spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/usuarios-db
    username: tmp
    password: tmppass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults=false: false
    database-platform: org.hibernate.dialect.PostgreSQL11Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

  profiles:
    active: test